export const effects = {
    "1": {
        "EFFECT_01": "",
        "POISON_SIDE_EFFECT1": "",
        "DRAIN_HP_EFFECT": "",
        "BURN_SIDE_EFFECT1": "",
        "FREEZE_SIDE_EFFECT": "",
        "PARALYZE_SIDE_EFFECT1": "",
        "EXPLODE_EFFECT": "",
        "DREAM_EATER_EFFECT": "",
        "MIRROR_MOVE_EFFECT": "",
        "ATTACK_UP1_EFFECT": "",
        "DEFENSE_UP1_EFFECT": "",
        "SPEED_UP1_EFFECT": "",
        "SPECIAL_UP1_EFFECT": "",
        "ACCURACY_UP1_EFFECT": "",
        "EVASION_UP1_EFFECT": "",
        "PAY_DAY_EFFECT": "",
        "SWIFT_EFFECT": "",
        "ATTACK_DOWN1_EFFECT": "",
        "DEFENSE_DOWN1_EFFECT": "",
        "SPEED_DOWN1_EFFECT": "",
        "SPECIAL_DOWN1_EFFECT": "",
        "ACCURACY_DOWN1_EFFECT": "",
        "EVASION_DOWN1_EFFECT": "",
        "CONVERSION_EFFECT": "",
        "HAZE_EFFECT": "",
        "BIDE_EFFECT": "",
        "THRASH_PETAL_DANCE_EFFECT": "",
        "SWITCH_AND_TELEPORT_EFFECT": "",
        "TWO_TO_FIVE_ATTACKS_EFFECT": "",
        "EFFECT_1E": "",
        "FLINCH_SIDE_EFFECT1": "",
        "SLEEP_EFFECT": "",
        "POISON_SIDE_EFFECT2": "",
        "BURN_SIDE_EFFECT2": "",
        // "unused": "",
        "PARALYZE_SIDE_EFFECT2": "",
        "FLINCH_SIDE_EFFECT2": "",
        "OHKO_EFFECT": "",
        "CHARGE_EFFECT": "",
        "SUPER_FANG_EFFECT": "",
        "SPECIAL_DAMAGE_EFFECT": "",
        "TRAPPING_EFFECT": "",
        "FLY_EFFECT": "",
        "ATTACK_TWICE_EFFECT": "",
        "JUMP_KICK_EFFECT": "",
        "MIST_EFFECT": "",
        "FOCUS_ENERGY_EFFECT": "",
        "RECOIL_EFFECT": "",
        "CONFUSION_EFFECT": "",
        "ATTACK_UP2_EFFECT": "",
        "DEFENSE_UP2_EFFECT": "",
        "SPEED_UP2_EFFECT": "",
        "SPECIAL_UP2_EFFECT": "",
        "ACCURACY_UP2_EFFECT": "",
        "EVASION_UP2_EFFECT": "",
        "HEAL_EFFECT": "",
        "TRANSFORM_EFFECT": "",
        "ATTACK_DOWN2_EFFECT": "",
        "DEFENSE_DOWN2_EFFECT": "",
        "SPEED_DOWN2_EFFECT": "",
        "SPECIAL_DOWN2_EFFECT": "",
        "ACCURACY_DOWN2_EFFECT": "",
        "EVASION_DOWN2_EFFECT": "",
        "LIGHT_SCREEN_EFFECT": "",
        "REFLECT_EFFECT": "",
        "POISON_EFFECT": "",
        "PARALYZE_EFFECT": "",
        "ATTACK_DOWN_SIDE_EFFECT": "",
        "DEFENSE_DOWN_SIDE_EFFECT": "",
        "SPEED_DOWN_SIDE_EFFECT": "",
        "SPECIAL_DOWN_SIDE_EFFECT": "",
        // "unused": "",
        // "unused": "",
        // "unused": "",
        // "unused": "",
        "CONFUSION_SIDE_EFFECT": "",
        "TWINEEDLE_EFFECT": "",
        // "unused": "",
        "SUBSTITUTE_EFFECT": "",
        "HYPER_BEAM_EFFECT": "",
        "RAGE_EFFECT": "",
        "MIMIC_EFFECT": "",
        "METRONOME_EFFECT": "",
        "LEECH_SEED_EFFECT": "",
        "SPLASH_EFFECT": "",
        "DISABLE_EFFECT": "",
    },
    "2" : {

    },
    "3" : {

    },
    "4" : {

    },
}