const megaStones = {
    "Mega Abomasnow":          "Abomasite",
    "Mega Absol":              "Absolite",
    "Mega Absol Z":            "Absolite Z",
    "Mega Aerodactyl":         "Aerodactylite",
    "Mega Aggron":             "Aggronite",
    "Mega Alakazam":           "Alakazite",
    "Mega Altaria":            "Altarianite",
    "Mega Ampharos":           "Ampharosite",
    "Mega Audino":             "Audinite",
    "Mega Banette":            "Banettite",
    "Mega Barbaracle":         "Barbaracite",
    "Mega Baxcalibur":         "Baxcalibrite",
    "Mega Beedrill":           "Beedrillite",
    "Mega Blastoise":          "Blastoisinite",
    "Mega Blaziken":           "Blazikenite",
    "Mega Camerupt":           "Cameruptite",
    "Mega Chandelure":         "Chandelurite",
    "Mega Charizard X":        "Charizardite X",
    "Mega Charizard Y":        "Charizardite Y",
    "Mega Chesnaught":         "Chesnaughtite",
    "Mega Chimecho":           "Chimechite",
    "Mega Clefable":           "Clefablite",
    "Mega Crabominable":       "Crabominite",
    "Mega Darkrai":            "Darkranite",
    "Mega Delphox":            "Delphoxite",
    "Mega Diancie":            "Diancite",
    "Mega Dragalge":           "Dragalgite",
    "Mega Dragonite":          "Dragoninite",
    "Mega Drampa":             "Drampanite",
    "Mega Eelektross":         "Eelektrossite",
    "Mega Emboar":             "Emboarite",
    "Mega Excadrill":          "Excadrite",
    "Mega Falinks":            "Falinksite",
    "Mega Feraligatr":         "Feraligite",
    "Mega Floette":            "Floettite",
    "Mega Froslass":           "Froslassite",
    "Mega Gallade":            "Galladite",
    "Mega Garchomp":           "Garchompite",
    "Mega Garchomp Z":         "Garchompite Z",
    "Mega Gardevoir":          "Gardevoirite",
    "Mega Gengar":             "Gengarite",
    "Mega Glalie":             "Glalitite",
    "Mega Glimmora":           "Glimmoranite",
    "Mega Golisopod":          "Golisopite",
    "Mega Golurk":             "Golurkite",
    "Mega Greninja":           "Greninjite",
    "Mega Gyarados":           "Gyaradosite",
    "Mega Hawlucha":           "Hawluchanite",
    "Mega Heatran":            "Heatranite",
    "Mega Heracross":          "Heracronite",
    "Mega Houndoom":           "Houndoominite",
    "Mega Kangaskhan":         "Kangaskhanite",
    "Mega Latias":             "Latiasite",
    "Mega Latios":             "Latiosite",
    "Mega Lopunny":            "Lopunnite",
    "Mega Lucario":            "Lucarionite",
    "Mega Lucario Z":          "Lucarionite Z",
    "Mega Magearna":           "Magearnite",
    "Mega Malamar":            "Malamarite",
    "Mega Manectric":          "Manectite",
    "Mega Mawile":             "Mawilite",
    "Mega Medicham":           "Medichamite",
    "Mega Meganium":           "Meganiumite",
    "Mega Meowstic":           "Meowsticite",
    "Mega Metagross":          "Metagrossite",
    "Mega Mewtwo X":           "Mewtwonite X",
    "Mega Mewtwo Y":           "Mewtwonite Y",
    "Mega Pidgeot":            "Pidgeotite",
    "Mega Pinsir":             "Pinsirite",
    "Mega Pyroar":             "Pyroarite",
    "Mega Raichu X":           "Raichunite X",
    "Mega Raichu Y":           "Raichunite Y",
    "Mega Sableye":            "Sablenite",
    "Mega Salamence":          "Salamencite",
    "Mega Sceptile":           "Sceptilite",
    "Mega Scizor":             "Scizorite",
    "Mega Scolipede":          "Scolipite",
    "Mega Scovillain":         "Scovillainite",
    "Mega Scrafty":            "Scraftinite",
    "Mega Sharpedo":           "Sharpedonite",
    "Mega Skarmory":           "Skarmorite",
    "Mega Slowbro":            "Slowbronite",
    "Mega Staraptor":          "Staraptite",
    "Mega Starmie":            "Starminite",
    "Mega Steelix":            "Steelixite",
    "Mega Swampert":           "Swampertite",
    "Mega Tatsugiri Curly":    "Tatsugirinite",
    "Mega Tatsugiri Droopy":   "Tatsugirinite",
    "Mega Tatsugiri Stretchy": "Tatsugirinite",
    "Mega Tyranitar":          "Tyranitarite",
    "Mega Venusaur":           "Venusaurite",
    "Mega Victreebel":         "Victreebelite",
    "Mega Zeraora":            "Zeraorite",
    "Mega Zygarde":            "Zygardite",
}
