export const version_exclusives = {
    "Red and Blue": {
        "Red": [
            "Ekans",
            "Arbok",
            "Oddish",
            "Gloom",
            "Vileplume",
            "Mankey",
            "Primeape",
            "Growlithe",
            "Arcanine",
            "Scyther",
            "Electabuzz",
        ],
        "Blue": [
            "Sandshrew",
            "Sandslash",
            "Vulpix",
            "Ninetales",
            "Meowth",
            "Persian",
            "Bellsprout",
            "Weepinbell",
            "Victreebel",
            "Magmar",
            "Pinsir",
        ],
    },
    "Gold and Silver": {
        "Gold": [
            "Mankey",
            "Primeape",
            "Growlithe",
            "Arcanine",
            "Spinarak",
            "Ariados",
            "Gligar",
            "Teddiursa",
            "Ursaring",
            "Mantine",
        ],
        "Silver": [
            "Vulpix",
            "Ninetales",
            "Meowth",
            "Persian",
            "Ledyba",
            "Ledian",
            "Delibird",
            "Skarmory",
            "Phanpy",
            "Donphan",
        ],
    },
    "Ruby and Sapphire": {
        "Ruby": [
            "Seedot",
            "Nuzleaf",
            "Shiftry",
            "Mawile",
            "Zangoose",
            "Solrock",
            "Latios",
            "Groudon",
        ],
        "Sapphire": [
            "Lotad",
            "Lombre",
            "Ludicolo",
            "Sableye",
            "Seviper",
            "Lunatone",
            "Latias",
            "Kyogre",
        ],
    },
    "FireRed and LeafGreen": {
        "FireRed": [
            "Ekans",
            "Arbok",
            "Oddish",
            "Gloom",
            "Vileplume",
            "Psyduck",
            "Golduck",
            "Growlithe",
            "Arcanine",
            "Shellder",
            "Cloyster",
            "Scyther",
            "Electabuzz",
            "Bellossom",
            "Wooper",
            "Quagsire",
            "Murkrow",
            "Qwilfish",
            "Delibird",
            "Skarmory",
            "Elekid",
        ],
        "LeafGreen": [
            "Sandshrew",
            "Sandslash",
            "Vulpix",
            "Ninetales",
            "Bellsprout",
            "Weepinbell",
            "Victreebel",
            "Slowpoke",
            "Slowbro",
            "Staryu",
            "Starmie",
            "Magmar",
            "Pinsir",
            "Marill",
            "Azumarill",
            "Misdreavus",
            "Sneasel",
            "Remoraid",
            "Octillery",
            "Mantine",
            "Magby",
            "Azurill",
        ],
    },
    "Diamond and Pearl": {
        "Diamond": [
            "Seel",
            "Dewgong",
            "Scyther",
            "Murkrow",
            "Larvitar",
            "Pupitar",
            "Tyranitar",
            "Poochyena",
            "Mightyena",
            "Aron",
            "Lairon",
            "Aggron",
            "Kecleon",
            "Cranidos",
            "Rampardos",
            "Honchkrow",
            "Stunky",
            "Skuntank",
            "Dialga",
        ],
        "Pearl": [
            "Slowpoke",
            "Slowbro",
            "Pinsir",
            "Misdreavus",
            "Houndour",
            "Houndoom",
            "Stantler",
            "Spheal",
            "Sealeo",
            "Walrein",
            "Bagon",
            "Shelgon",
            "Salamence",
            "Shieldon",
            "Bastiodon",
            "Mismagius",
            "Glameow",
            "Purugly",
            "Palkia",
        ],
    },
    "HeartGold and SoulSilver": {
        "HeartGold": [
            "Mankey",
            "Primeape",
            "Growlithe",
            "Arcanine",
            "Omanyte",
            "Omastar",
            "Spinarak",
            "Ariados",
            "Gligar",
            "Mantine",
            "Phanpy",
            "Donphan",
            "Sableye",
            "Baltoy",
            "Claydol",
            "Anorith",
            "Armaldo",
            "Latias",
            "Kyogre",
            "Mantyke",
            "Gliscor",
        ],
        "SoulSilver": [
            "Vulpix",
            "Ninetales",
            "Meowth",
            "Persian",
            "Kabuto",
            "Kabutops",
            "Ledyba",
            "Ledian",
            "Teddiursa",
            "Ursaring",
            "Delibird",
            "Skarmory",
            "Mawile",
            "Gulpin",
            "Swalot",
            "Lileep",
            "Cradily",
            "Latios",
            "Groudon",
        ],
    },
    "Black and White": {
        "Black": [
            "Weedle",
            "Kakuna",
            "Beedrill",
            "Murkrow",
            "Houndour",
            "Houndoom",
            "Shroomish",
            "Breloom",
            "Plusle",
            "Honchkrow",
            "Gothita",
            "Gothorita",
            "Gothitelle",
            "Vullaby",
            "Mandibuzz",
            "Tornadus",
            "Reshiram",
        ],
        "White": [
            "Caterpie",
            "Metapod",
            "Butterfree",
            "Paras",
            "Parasect",
            "Misdreavus",
            "Poochyena",
            "Mightyena",
            "Minun",
            "Mismagius",
            "Solosis",
            "Duosion",
            "Reuniclus",
            "Rufflet",
            "Braviary",
            "Thundurus",
            "Zekrom",
            "Pidgey",
            "Pidgeotto",
            "Pidgeot",
            "Nidoran F",
            "Nidorina",
            "Nidoqueen",
            "Nidoran M",
            "Nidorino",
            "Nidoking",
            "Oddish",
            "Gloom",
            "Vileplume",
            "Abra",
            "Kadabra",
            "Machop",
            "Machoke",
            "Bellsprout",
            "Weepinbell",
            "Victreebel",
            "Magnemite",
            "Magneton",
            "Gastly",
            "Haunter",
            "Rhyhorn",
            "Rhydon",
            "Chansey",
            "Electabuzz",
            "Magmar",
            "Porygon",
            "Togepi",
            "Togetic",
            "Mareep",
            "Flaaffy",
            "Ampharos",
            "Bellossom",
            "Marill",
            "Azumarill",
            "Hoppip",
            "Skiploom",
            "Jumpluff",
            "Wooper",
            "Quagsire",
            "Elekid",
            "Magby",
            "Blissey",
            "Wurmple",
            "Silcoon",
            "Beautifly",
            "Cascoon",
            "Dustox",
            "Lotad",
            "Lombre",
            "Ludicolo",
            "Seedot",
            "Nuzleaf",
            "Shiftry",
            "Ralts",
            "Kirlia",
            "Gardevoir",
            "Surskit",
            "Masquerain",
            "Slakoth",
            "Vigoroth",
            "Slaking",
            "Whismur",
            "Loudred",
            "Exploud",
            "Azurill",
            "Aron",
            "Lairon",
            "Aggron",
            "Roselia",
            "Trapinch",
            "Vibrava",
            "Flygon",
            "Corphish",
            "Crawdaunt",
            "Bagon",
            "Shelgon",
            "Salamence",
            "Starly",
            "Staravia",
            "Staraptor",
            "Shinx",
            "Luxio",
            "Luxray",
            "Budew",
            "Roserade",
            "Happiny",
            "Magnezone",
            "Togekiss",
            "Gallade",
        ],
    },
    "Black 2 and White 2": {
        "Black 2": [
            "Weedle",
            "Kakuna",
            "Beedrill",
            "Magmar",
            "Spinarak",
            "Ariados",
            "Sudowoodo",
            "Magby",
            "Plusle",
            "Spoink",
            "Grumpig",
            "Registeel",
            "Latios",
            "Buneary",
            "Lopunny",
            "Stunky",
            "Skuntank",
            "Bonsly",
            "Gible",
            "Gabite",
            "Garchomp",
            "Magmortar",
            "Gothita",
            "Gothorita",
            "Gothitelle",
            "Vullaby",
            "Mandibuzz",
            "Zekrom",
            "Kyurem (Black)",
        ],
        "White 2": [
            "Caterpie",
            "Metapod",
            "Butterfree",
            "Mr. Mime",
            "Electabuzz",
            "Ledyba",
            "Ledian",
            "Elekid",
            "Skitty",
            "Delcatty",
            "Minun",
            "Numel",
            "Camerupt",
            "Regice",
            "Latias",
            "Glameow",
            "Purugly",
            "Mime Jr.",
            "Electivire",
            "Solosis",
            "Duosion",
            "Reuniclus",
            "Rufflet",
            "Braviary",
            "Reshiram",
            "Kyurem (White)",
        ],
    },
    "X and Y": {
        "X": [
            "Mega Charizard X",
            "Staryu",
            "Starmie",
            "Pinsir",
            "Mega Mewtwo X",
            "Houndour",
            "Houndoom",
            "Poochyena",
            "Mightyena",
            "Aron",
            "Lairon",
            "Aggron",
            "Lileep",
            "Cradily",
            "Anorith",
            "Armaldo",
            "Sawk",
            "Swirlix",
            "Clauncher",
            "Clawitzer",
            "Xerneas",
        ],
        "Y": [
            "Mega Charizard Y",
            "Shellder",
            "Cloyster",
            "Omanyte",
            "Omastar",
            "Kabuto",
            "Kabutops",
            "Mega Mewtwo Y",
            "Heracross",
            "Larvitar",
            "Pupitar",
            "Tyranitar",
            "Electrike",
            "Manectric",
            "Purrloin",
            "Liepard",
            "Throh",
            "Spritzee",
            "Skrelp",
            "Dragalge",
            "Yveltal",
        ],
    },
    "Omega Ruby and Alpha Sapphire": {
        "Omega Ruby": [
            "Kabuto",
            "Kabutops",
            "Ho-Oh",
            "Seedot",
            "Nuzleaf",
            "Shiftry",
            "Mawile",
            "Zangoose",
            "Solrock",
            "Latios",
            "Groudon",
            "Shieldon",
            "Bastiodon",
            "Shellos (West Sea)",
            "Gastrodon (West Sea)",
            "Palkia",
            "Throh",
            "Archen",
            "Archeops",
            "Tornadus",
            "Reshiram",
            "Skrelp",
            "Dragalge",
        ],
        "Alpha Sapphire": [
            "Omanyte",
            "Omastar",
            "Lugia",
            "Lotad",
            "Lombre",
            "Ludicolo",
            "Sableye",
            "Seviper",
            "Lunatone",
            "Latias",
            "Kyogre",
            "Cranidos",
            "Rampardos",
            "Shellos (East Sea)",
            "Gastrodon (East Sea)",
            "Dialga",
            "Sawk",
            "Tirtouga",
            "Carracosta",
            "Thundurus",
            "Zekrom",
            "Clauncher",
            "Clawitzer",
        ],
    },
    "Sun and Moon": {
        "Sun": [
            "Alolan Vulpix",
            "Alolan Ninetales",
            "Cranidos",
            "Rampardos",
            "Cottonee",
            "Whimsicott",
            "Tirtouga",
            "Carracosta",
            "Rufflet",
            "Braviary",
            "Passimian",
            "Turtonator",
            "Solgaleo",
            "Buzzwole",
            "Kartana",
        ],
        "Moon": [
            "Alolan Sandshrew",
            "Alolan Sandslash",
            "Shieldon",
            "Bastiodon",
            "Petilil",
            "Lilligant",
            "Archen",
            "Archeops",
            "Vullaby",
            "Mandibuzz",
            "Oranguru",
            "Drampa",
            "Lunala",
            "Pheromosa",
            "Celesteela",
        ],
    },
    "Ultra Sun and Ultra Moon": {
        "Ultra Sun": [
            "Alolan Vulpix",
            "Alolan Ninetales",
            "Houndour",
            "Houndoom",
            "Raikou",
            "Ho-Oh",
            "Latios",
            "Groudon",
            "Dialga",
            "Heatran",
            "Cottonee",
            "Whimsicott",
            "Basculin",
            "Golett",
            "Golurk",
            "Rufflet",
            "Braviary",
            "Tornadus",
            "Reshiram",
            "Clauncher",
            "Clawitzer",
            "Xerneas",
            "Passimian",
            "Turtonator",
            "Solgaleo",
            "Buzzwole",
            "Kartana",
            "Blacephalon",
            "Alolan Marowak",
            "Gumshoos",
            "Vikavolt",
            "Ribombee",
            "Lurantis",
        ],
        "Ultra Moon": [
            "Alolan Sandshrew",
            "Alolan Sandslash",
            "Entei",
            "Lugia",
            "Electrike",
            "Manectric",
            "Baltoy",
            "Claydol",
            "Latias",
            "Kyogre",
            "Palkia",
            "Regigigas",
            "Petilil",
            "Lilligant",
            "Basculin (Blue Striped)",
            "Vullaby",
            "Mandibuzz",
            "Thundurus",
            "Zekrom",
            "Skrelp",
            "Dragalge",
            "Yveltal",
            "Oranguru",
            "Drampa",
            "Lunala",
            "Pheromosa",
            "Celesteela",
            "Stakataka",
            "Alolan Raticate",
            "Araquanid",
            "Salazzle",
            "Togedemaru",
            "Kommo-o",
        ],
    },
    "Let's Go Pikachu and Let's Go Eevee": {
        "Let's Go Pikachu": [
            "Partner Pikachu",
            "Sandshrew",
            "Alolan Sandshrew",
            "Sandslash",
            "Alolan Sandslash",
            "Oddish",
            "Gloom",
            "Vileplume",
            "Mankey",
            "Primeape",
            "Growlithe",
            "Grimer",
            "Alolan Grimer",
            "Muk",
            "Alolan Muk",
            "Scyther",
        ],
        "Let's Go Eevee": [
            "Ekans",
            "Arbok",
            "Vulpix",
            "Alolan Vulpix",
            "Ninetales",
            "Alolan Ninetales",
            "Meowth",
            "Alolan Meowth",
            "Alolan Persian",
            "Bellsprout",
            "Weepinbell",
            "Victreebel",
            "Koffing",
            "Weezing",
            "Pinsir",
            "Partner Eevee",
        ],
    },
    "Sword and Shield": {
        "Sword": [
            "Galarian Farfetch'd",
            "Seedot",
            "Nuzleaf",
            "Shiftry",
            "Mawile",
            "Solrock",
            "Basculin",
            "Galarian Darumaka",
            "Galarian Darmanitan",
            "Scraggy",
            "Scrafty",
            "Gothita",
            "Gothorita",
            "Gothitelle",
            "Rufflet",
            "Braviary",
            "Deino",
            "Zweilous",
            "Hydreigon",
            "Swirlix",
            "Turtonator",
            "Jangmo-o",
            "Hakamo-o",
            "Kommo-o",
            "Flapple",
            "Sirfetch'd",
            "Stonjourner",
            "Zacian",
            "Pinsir",
            "Clauncher",
            "Clawitzer",
            "Omanyte",
            "Omastar",
            "Ho-Oh",
            "Bagon",
            "Shelgon",
            "Salamence",
            "Latios",
            "Groudon",
            "Dialga",
            "Tornadus",
            "Reshiram",
            "Xerneas",
            "Solgaleo",
            "Gigantamax Machamp",
            "Gigantamax Coalossal",
            "Gigantamax Flapple",
        ],
        "Shield": [
            "Galarian Ponyta",
            "Galarian Rapidash",
            "Galarian Corsola",
            "Larvitar",
            "Pupitar",
            "Tyranitar",
            "Lotad",
            "Lombre",
            "Ludicolo",
            "Sableye",
            "Lunatone",
            "Croagunk",
            "Toxicroak",
            "Basculin (Blue Striped)",
            "Solosis",
            "Duosion",
            "Reuniclus",
            "Vullaby",
            "Mandibuzz",
            "Spritzee",
            "Goomy",
            "Sliggoo",
            "Goodra",
            "Drampa",
            "Appletun",
            "Cursola",
            "Eiscue",
            "Zamazenta",
            "Heracross",
            "Skrelp",
            "Dragalge",
            "Kabuto",
            "Kabutops",
            "Lugia",
            "Latias",
            "Kyogre",
            "Gible",
            "Gabite",
            "Garchomp",
            "Palkia",
            "Thundurus",
            "Zekrom",
            "Yveltal",
            "Lunala",
            "Gigantamax Gengar",
            "Gigantamax Lapras",
            "Gigantamax Appletun",
        ],
    },
    "Brilliant Diamond and Shining Pearl": {
        "Brilliant Diamond": [
            "Caterpie",
            "Metapod",
            "Butterfree",
            "Ekans",
            "Arbok",
            "Growlithe",
            "Arcanine",
            "Seel",
            "Dewgong",
            "Scyther",
            "Electabuzz",
            "Murkrow",
            "Gligar",
            "Elekid",
            "Raikou",
            "Entei",
            "Suicune",
            "Larvitar",
            "Pupitar",
            "Tyranitar",
            "Ho-Oh",
            "Seedot",
            "Nuzleaf",
            "Shiftry",
            "Mawile",
            "Zangoose",
            "Solrock",
            "Kecleon",
            "Cranidos",
            "Rampardos",
            "Honchkrow",
            "Stunky",
            "Skuntank",
            "Gliscor",
            "Dialga",
        ],
        "Shining Pearl": [
            "Weedle",
            "Kakuna",
            "Beedrill",
            "Sandshrew",
            "Sandslash",
            "Vulpix",
            "Ninetales",
            "Slowpoke",
            "Slowbro",
            "Magmar",
            "Pinsir",
            "Articuno",
            "Zapdos",
            "Moltres",
            "Misdreavus",
            "Teddiursa",
            "Ursaring",
            "Stantler",
            "Magby",
            "Lugia",
            "Lotad",
            "Lombre",
            "Ludicolo",
            "Sableye",
            "Seviper",
            "Lunatone",
            "Bagon",
            "Shelgon",
            "Salamence",
            "Shieldon",
            "Bastiodon",
            "Mismagius",
            "Glameow",
            "Purugly",
            "Palkia",
        ],
    },
    "Scarlet and Violet": {
        "Scarlet": [
            "Tauros (Paldea Blaze Breed)",
            "Larvitar",
            "Pupitar",
            "Tyranitar",
            "Drifloon",
            "Drifblim",
            "Stunky",
            "Skuntank",
            "Dialga",
            "Deino",
            "Zweilous",
            "Hydreigon",
            "Skrelp",
            "Dragalge",
            "Oranguru",
            "Stonjourner",
            "Armarouge",
            "Great Tusk",
            "Scream Tail",
            "Brute Bonnet",
            "Flutter Mane",
            "Slither Wing",
            "Sandy Shocks",
            "Roaring Moon",
            "Koraidon",
            "Walking Wake",
            "Gligar",
            "Gliscor",
            "Cramorant",
            "Alolan Vulpix",
            "Alolan Ninetales",
            "Raikou",
            "Entei",
            "Suicune",
            "Ho-Oh",
            "Latios",
            "Groudon",
            "Cranidos",
            "Rampardos",
            "Reshiram",
            "Kyurem (White)",
            "Solgaleo",
            "Necrozma (Dusk)",
            "Glastrier",
            "Gouging Fire",
            "Raging Bolt",
        ],
        "Violet": [
            "Tauros (Paldea Aqua Breed)",
            "Misdreavus",
            "Bagon",
            "Shelgon",
            "Salamence",
            "Mismagius",
            "Palkia",
            "Clauncher",
            "Clawitzer",
            "Passimian",
            "Eiscue",
            "Dreepy",
            "Drakloak",
            "Dragapult",
            "Ceruledge",
            "Iron Treads",
            "Iron Bundle",
            "Iron Hands",
            "Iron Jugulis",
            "Iron Moth",
            "Iron Thorns",
            "Iron Valiant",
            "Miraidon",
            "Iron Leaves",
            "Aipom",
            "Ambipom",
            "Morpeko",
            "Alolan Sandshrew",
            "Alolan Sandslash",
            "Lugia",
            "Latias",
            "Kyogre",
            "Shieldon",
            "Bastiodon",
            "Cobalion",
            "Terrakion",
            "Virizion",
            "Zekrom",
            "Kyurem (Black)",
            "Lunala",
            "Necrozma (Dawn)",
            "Spectrier",
            "Iron Boulder",
            "Iron Crown",
        ],
    },
};
